# Generated by Django 4.2 on 2026-01-03 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Movie title', max_length=200)),
                ('director', models.CharField(help_text='Director name', max_length=100)),
                ('genre', models.CharField(help_text='Movie genre', max_length=100)),
                ('year', models.IntegerField(help_text='Release year (1800-2100)', validators=[django.core.validators.MinValueValidator(1800, message='Year must be at least 1800'), django.core.validators.MaxValueValidator(2100, message='Year cannot exceed 2100')])),
                ('rating', models.FloatField(help_text='Movie rating (0-10)', validators=[django.core.validators.MinValueValidator(0.0, message='Rating must be at least 0'), django.core.validators.MaxValueValidator(10.0, message='Rating cannot exceed 10')])),
                ('budget', models.IntegerField(blank=True, help_text='Production budget (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-year', '-rating'],
            },
        ),
    ]
